name: Build and Deploy Sphinx Docs

on:
  push:
    branches:
      - main
      - documentation-update
    paths:
      - 'docs/**'
      - '!docs/_build/**' # No infinite loop from pushing to docs again
      - '.github/workflows/build-docs.yml'
  workflow_dispatch:

permissions:
  contents: write   # pushing commits
  pages: write      #  GH Pages deploy
  id-token: write   # GH Pages OIDC

concurrency:
  group: "pages-${{ github.ref }}"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install . # Install current package for autodoc, etc.
          
          # Sphinx and its bits
          pip install sphinx finaletoolkit pydata_sphinx_theme sphinx-argparse
          # Consider a docs/requirements.txt for these

      - name: Build Sphinx documentation
        run: |
          cd docs
          make html
          touch _build/html/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/_build/html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
